export const images = {
  bg_hero: "/images/bg_hero.png",
  logo: "/logo.png",
  workers: "/images/workers.png",
  facade: "/images/facade.png",
  ceiling: "/images/ceiling.png",
  foil: "/images/foil.png",
  house: "/images/house.png",
  drywall: "/images/drywall.png",
  tiles: "/images/tiles.png",
  painting: "/images/painting.png",
  insulation: "/images/insulation.png",
  reconstruction: "/images/reconstruction.png",
  plumbing: "/images/plumbing.png",
  demolition: "/images/demolition.png",
  earthworks: "/images/earthworks.png",
  project1: "/images/project1.png",
  project2: "/images/project2.png",
  project3: "/images/project3.png",
  project4: "/images/project4.png",
};
